/**
 * Tailwind CSS Configuration
 * Generated by Synkio
 * https://github.com/rgehrkedk/synkio
 */

/** @type {import("tailwindcss").Config} */
export default {
  theme: {
    extend: {
        spacing: {
          default: {
            spacing: {
              xs: '0.25rem',
              sm: '0.5rem',
              md: '1rem',
              lg: '1.5rem',
              xl: '2rem',
              '2xl': '3rem',
              '3xl': '4rem',
            },
          },
        },
        borderRadius: {
          default: {
            radius: {
              none: '0',
              sm: '0.25rem',
              md: '0.5rem',
              lg: '0.75rem',
              full: '624.938rem',
            },
          },
        },
        colors: {
          primary: {
            '50': '#eef2ff',
            '100': '#e0e7ff',
            '200': '#c7d2fe',
            '300': '#a5b4fc',
            '400': '#818cf8',
            '500': '#6366f1',
            '600': '#4f46e5',
            '700': '#4338ca',
            '800': '#3730a3',
            '900': '#312e81',
          },
          neutral: {
            '50': '#fafafa',
            '100': '#f5f5f5',
            '200': '#e5e5e5',
            '300': '#d4d4d4',
            '400': '#a3a3a3',
            '500': '#737373',
            '600': '#525252',
            '700': '#404040',
            '800': '#262626',
            '900': '#171717',
          },
          success: {
            '500': '#22c55e',
          },
          warning: {
            '500': '#f59e0b',
          },
          error: {
            '500': '#ef4444',
          },
          background: {
            primary: '#ffffff',
            secondary: '#f5f5f5',
          },
          text: {
            primary: '#171717',
            secondary: '#525252',
          },
        },
        fontSize: {
          default: {
            font: {
              size: {
                xs: '0.75rem',
                sm: '0.875rem',
                base: '1rem',
                lg: '1.125rem',
                xl: '1.25rem',
                '2xl': '1.5rem',
                '3xl': '1.875rem',
                '4xl': '2.25rem',
              },
            },
          },
        },
        fontWeight: {
          default: {
            font: {
              weight: {
                normal: '400',
                medium: '500',
                semibold: '600',
                bold: '700',
              },
            },
          },
        },
        lineHeight: {
          default: {
            font: {
              lineHeight: {
                tight: '1.25',
                normal: '1.5',
                relaxed: '1.75',
              },
            },
          },
        },
      },
  },
};