/**
 * Design Tokens
 * Generated by Synkio
 * https://github.com/rgehrkedk/synkio
 * @generated
 */
export const tokens = {
  default: {
    spacing: {
      xs: '4px',
      sm: '8px',
      md: '16px',
      lg: '24px',
      xl: '32px',
      '2xl': '48px',
      '3xl': '64px',
    },
    radius: {
      none: '0',
      sm: '4px',
      md: '8px',
      lg: '12px',
      full: '9999px',
    },
    font: {
      size: {
        xs: '12px',
        sm: '14px',
        base: '16px',
        lg: '18px',
        xl: '20px',
        '2xl': '24px',
        '3xl': '30px',
        '4xl': '36px',
      },
      weight: {
        normal: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
      },
      lineHeight: {
        tight: '1.25',
        normal: '1.5',
        relaxed: '1.75',
      },
    },
  },
  color: {
    primary: {
      '50': '#eef2ff',
      '100': '#e0e7ff',
      '200': '#c7d2fe',
      '300': '#a5b4fc',
      '400': '#818cf8',
      '500': '#6366f1',
      '600': '#4f46e5',
      '700': '#4338ca',
      '800': '#3730a3',
      '900': '#312e81',
    },
    neutral: {
      '50': '#fafafa',
      '100': '#f5f5f5',
      '200': '#e5e5e5',
      '300': '#d4d4d4',
      '400': '#a3a3a3',
      '500': '#737373',
      '600': '#525252',
      '700': '#404040',
      '800': '#262626',
      '900': '#171717',
    },
    success: {
      '500': '#22c55e',
    },
    warning: {
      '500': '#f59e0b',
    },
    error: {
      '500': '#ef4444',
    },
    background: {
      primary: '#ffffff',
      secondary: '#f5f5f5',
    },
    text: {
      primary: '#171717',
      secondary: '#525252',
    },
  },
} as const;

// light mode overrides
export const tokensLight = {
  bg: {
    primary: {
      default: '[object Object]',
    },
  },
} as const;

// dark mode overrides
export const tokensDark = {
  bg: {
    primary: {
      default: '[object Object]',
    },
  },
} as const;