/**
 * Style Dictionary Scaffolding
 *
 * Generate basic Style Dictionary configuration for new projects.
 */

import fs from 'fs';
import path from 'path';

// ============================================================================
// Types
// ============================================================================

export interface ScaffoldOptions {
  tokensPath: string;
  outputPath: string;
  platforms: ('css' | 'scss' | 'js' | 'ts')[];
  useEsm: boolean;
}

// ============================================================================
// Scaffolding
// ============================================================================

/**
 * Generate Style Dictionary config content
 */
export function generateStyleDictionaryConfig(options: ScaffoldOptions): string {
  const { tokensPath, outputPath, platforms, useEsm } = options;

  const platformConfigs: string[] = [];

  if (platforms.includes('css')) {
    platformConfigs.push(`
    css: {
      transformGroup: 'css',
      buildPath: '${outputPath}/',
      files: [
        {
          destination: 'variables.css',
          format: 'css/variables',
        },
      ],
    }`);
  }

  if (platforms.includes('scss')) {
    platformConfigs.push(`
    scss: {
      transformGroup: 'scss',
      buildPath: '${outputPath}/',
      files: [
        {
          destination: '_variables.scss',
          format: 'scss/variables',
        },
      ],
    }`);
  }

  if (platforms.includes('js')) {
    platformConfigs.push(`
    js: {
      transformGroup: 'js',
      buildPath: '${outputPath}/',
      files: [
        {
          destination: 'tokens.js',
          format: 'javascript/es6',
        },
      ],
    }`);
  }

  if (platforms.includes('ts')) {
    platformConfigs.push(`
    ts: {
      transformGroup: 'js',
      buildPath: '${outputPath}/',
      files: [
        {
          destination: 'tokens.ts',
          format: 'javascript/es6',
        },
        {
          destination: 'tokens.d.ts',
          format: 'typescript/es6-declarations',
        },
      ],
    }`);
  }

  if (useEsm) {
    return `/**
 * Style Dictionary Configuration
 *
 * Generated by figma-sync setup
 * https://styledictionary.com/
 */

export default {
  source: ['${tokensPath}/**/*.json'],
  platforms: {${platformConfigs.join(',')}\n  },
};
`;
  } else {
    return `/**
 * Style Dictionary Configuration
 *
 * Generated by figma-sync setup
 * https://styledictionary.com/
 */

module.exports = {
  source: ['${tokensPath}/**/*.json'],
  platforms: {${platformConfigs.join(',')}\n  },
};
`;
  }
}

/**
 * Generate build script for package.json
 */
export function generateBuildScript(useEsm: boolean): string {
  if (useEsm) {
    return 'style-dictionary build --config style-dictionary.config.mjs';
  }
  return 'style-dictionary build';
}

/**
 * Scaffold Style Dictionary setup
 */
export function scaffoldStyleDictionary(options: ScaffoldOptions): {
  configPath: string;
  buildCommand: string;
} {
  const ext = options.useEsm ? 'mjs' : 'js';
  const configPath = `style-dictionary.config.${ext}`;
  const content = generateStyleDictionaryConfig(options);

  // Write config file
  fs.writeFileSync(configPath, content);

  // Generate build command
  const buildCommand = generateBuildScript(options.useEsm);

  return {
    configPath,
    buildCommand,
  };
}

/**
 * Check if project uses ESM (ES modules)
 */
export function detectModuleType(): 'esm' | 'cjs' {
  const packageJsonPath = 'package.json';

  if (!fs.existsSync(packageJsonPath)) {
    return 'cjs';
  }

  try {
    const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf-8'));
    return packageJson.type === 'module' ? 'esm' : 'cjs';
  } catch {
    return 'cjs';
  }
}

/**
 * Add build script to package.json
 */
export function addBuildScript(scriptName: string, command: string): boolean {
  const packageJsonPath = 'package.json';

  if (!fs.existsSync(packageJsonPath)) {
    return false;
  }

  try {
    const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf-8'));

    if (!packageJson.scripts) {
      packageJson.scripts = {};
    }

    // Don't overwrite existing script
    if (packageJson.scripts[scriptName]) {
      return false;
    }

    packageJson.scripts[scriptName] = command;

    fs.writeFileSync(packageJsonPath, JSON.stringify(packageJson, null, 2) + '\n');
    return true;
  } catch {
    return false;
  }
}
