/**
 * Layout component - the main wrapper for all documentation pages
 */
import type { TemplateOptions } from './types.js';
import { getPageTitle } from './utils.js';
import { renderSidebar } from './sidebar.js';
import { renderHeaderControls } from './header-controls.js';

interface LayoutProps {
  content: string;
  options: TemplateOptions;
  activePage: string;
  /** Optional: mode toggle HTML to render below the header */
  modeToggleHtml?: string;
}

/**
 * Generate the complete HTML page layout
 */
export function layout({ content, options, activePage, modeToggleHtml }: LayoutProps): string {
  const { title, syncedAt, navItems } = options;
  const formattedDate = new Date(syncedAt).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  // Default platform is always 'json' since we always have JSON path format
  const defaultPlatform = 'json';

  return `<!DOCTYPE html>
<html lang="en" data-theme="dark" data-mode="${options.defaultMode}" data-platform="${defaultPlatform}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title} - Synkio Docs</title>
  <link rel="stylesheet" href="assets/tokens.css">
  <link rel="stylesheet" href="assets/utilities.css">
  <link rel="stylesheet" href="assets/docs.css">
</head>
<body>
  <div class="docs-layout">
    ${renderSidebar({ title, navItems, activePage })}

    <!-- Main content -->
    <main class="docs-main">
      <header class="docs-header">
        <div>
          <h1 class="docs-title">${getPageTitle(activePage)}</h1>
          <p class="docs-subtitle">Last synced: ${formattedDate}</p>
        </div>

        ${renderHeaderControls({
          platforms: ['json'],
          defaultPlatform
        })}
      </header>

      ${modeToggleHtml || ''}

      ${content}

      <footer class="docs-footer">
        <span>Generated by <a href="https://github.com/rgehrkedk/synkio" target="_blank">Synkio</a></span>
        <span>Last updated: ${formattedDate}</span>
        ${options.metadata ? `
        <span>Output mode: JSON</span>
        ${options.metadata.output.css?.enabled ? `<span>CSS transforms enabled</span>` : ''}
        ` : ''}
      </footer>
    </main>
  </div>

  <button class="docs-mobile-toggle" id="mobileToggle">
    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
      <line x1="3" y1="12" x2="21" y2="12"/>
      <line x1="3" y1="6" x2="21" y2="6"/>
      <line x1="3" y1="18" x2="21" y2="18"/>
    </svg>
  </button>

  <div class="docs-copied" id="copiedToast">Copied to clipboard!</div>

  <script src="assets/preview.js"></script>
</body>
</html>`;
}
