/**
 * Generate minimal JavaScript for interactivity
 */
export function generatePreviewJS(): string {
  return `/**
 * Synkio Documentation - Interactive Features
 * Generated by Synkio
 */

(function() {
  'use strict';

  // DOM Elements
  const searchInput = document.getElementById('searchInput');
  const themeToggle = document.getElementById('themeToggle');
  const mobileToggle = document.getElementById('mobileToggle');
  const sidebar = document.querySelector('.docs-sidebar');
  const copiedToast = document.getElementById('copiedToast');
  const modeBtns = document.querySelectorAll('.docs-mode-btn');

  // ============================================
  // Theme Toggle (Light/Dark)
  // ============================================
  
  function initTheme() {
    const savedTheme = localStorage.getItem('synkio-docs-theme') || 'dark';
    document.documentElement.setAttribute('data-theme', savedTheme);
  }

  function toggleTheme() {
    const current = document.documentElement.getAttribute('data-theme');
    const next = current === 'dark' ? 'light' : 'dark';
    document.documentElement.setAttribute('data-theme', next);
    localStorage.setItem('synkio-docs-theme', next);
  }

  if (themeToggle) {
    themeToggle.addEventListener('click', toggleTheme);
  }

  initTheme();

  // ============================================
  // Mode Switcher (Light/Dark tokens, etc.)
  // ============================================

  function initMode() {
    const savedMode = localStorage.getItem('synkio-docs-mode');
    if (savedMode) {
      document.documentElement.setAttribute('data-mode', savedMode);
      updateModeButtons(savedMode);
    }
  }

  function setMode(mode) {
    document.documentElement.setAttribute('data-mode', mode);
    localStorage.setItem('synkio-docs-mode', mode);
    updateModeButtons(mode);
    
    // Filter tokens by mode if we're showing mode-specific content
    filterByMode(mode);
  }

  function updateModeButtons(activeMode) {
    modeBtns.forEach(btn => {
      if (btn.dataset.mode === activeMode) {
        btn.classList.add('active');
      } else {
        btn.classList.remove('active');
      }
    });
  }

  function filterByMode(mode) {
    // Show/hide token cards based on mode
    const tokenCards = document.querySelectorAll('[data-token]');
    tokenCards.forEach(card => {
      const cardMode = card.dataset.mode;
      if (!cardMode || cardMode === mode) {
        card.style.display = '';
      } else {
        card.style.display = 'none';
      }
    });
  }

  modeBtns.forEach(btn => {
    btn.addEventListener('click', () => setMode(btn.dataset.mode));
  });

  initMode();

  // ============================================
  // Search
  // ============================================

  function debounce(fn, delay) {
    let timeout;
    return function(...args) {
      clearTimeout(timeout);
      timeout = setTimeout(() => fn.apply(this, args), delay);
    };
  }

  function searchTokens(query) {
    const normalizedQuery = query.toLowerCase().trim();
    const tokenElements = document.querySelectorAll('[data-token]');
    const rows = document.querySelectorAll('.docs-token-table tbody tr');
    
    // Search in card view
    tokenElements.forEach(el => {
      if (!el.matches('tr')) {
        const tokenPath = (el.dataset.token || '').toLowerCase();
        const textContent = el.textContent.toLowerCase();
        const matches = !normalizedQuery || tokenPath.includes(normalizedQuery) || textContent.includes(normalizedQuery);
        el.style.display = matches ? '' : 'none';
      }
    });
    
    // Search in table view
    rows.forEach(row => {
      const tokenPath = (row.dataset.token || '').toLowerCase();
      const textContent = row.textContent.toLowerCase();
      const matches = !normalizedQuery || tokenPath.includes(normalizedQuery) || textContent.includes(normalizedQuery);
      row.style.display = matches ? '' : 'none';
    });
    
    // Update section visibility
    updateSectionVisibility();
  }

  function updateSectionVisibility() {
    const sections = document.querySelectorAll('.docs-section');
    sections.forEach(section => {
      const grid = section.querySelector('.docs-token-grid');
      if (grid) {
        const visibleCards = grid.querySelectorAll('.docs-token-card:not([style*="display: none"])');
        section.style.display = visibleCards.length > 0 ? '' : 'none';
      }
    });
  }

  if (searchInput) {
    searchInput.addEventListener('input', debounce((e) => {
      searchTokens(e.target.value);
    }, 150));
    
    // Clear search on Escape
    searchInput.addEventListener('keydown', (e) => {
      if (e.key === 'Escape') {
        searchInput.value = '';
        searchTokens('');
      }
    });
  }

  // ============================================
  // Copy to Clipboard
  // ============================================

  function showCopiedToast() {
    copiedToast.classList.add('show');
    setTimeout(() => {
      copiedToast.classList.remove('show');
    }, 2000);
  }

  async function copyToClipboard(text) {
    try {
      await navigator.clipboard.writeText(text);
      showCopiedToast();
    } catch (err) {
      // Fallback for older browsers
      const textarea = document.createElement('textarea');
      textarea.value = text;
      textarea.style.position = 'fixed';
      textarea.style.opacity = '0';
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
      showCopiedToast();
    }
  }

  // Click to copy on elements with data-copy attribute
  document.addEventListener('click', (e) => {
    const copyable = e.target.closest('[data-copy]');
    if (copyable) {
      e.preventDefault();
      copyToClipboard(copyable.dataset.copy);
    }
  });

  // ============================================
  // Mobile Menu
  // ============================================

  if (mobileToggle && sidebar) {
    mobileToggle.addEventListener('click', () => {
      sidebar.classList.toggle('open');
    });
    
    // Close on outside click
    document.addEventListener('click', (e) => {
      if (sidebar.classList.contains('open') && 
          !sidebar.contains(e.target) && 
          !mobileToggle.contains(e.target)) {
        sidebar.classList.remove('open');
      }
    });
  }

  // ============================================
  // Keyboard Navigation
  // ============================================

  document.addEventListener('keydown', (e) => {
    // Focus search with Cmd/Ctrl + K
    if ((e.metaKey || e.ctrlKey) && e.key === 'k') {
      e.preventDefault();
      if (searchInput) {
        searchInput.focus();
        searchInput.select();
      }
    }
  });

  // ============================================
  // Initialize
  // ============================================

  console.log('Synkio Docs initialized');
})();
`;
}
